import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    background: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: '100%',
        width: '100%',
    },
    
    containerLogin: {
        backgroundColor: '#A3D8EE',
        borderColor: '#0000000',
        borderWidth: 2,
        borderRadius: 15,
        paddingTop: 0,
        margin: 30,
        marginBottom: 0,
        marginTop: 10,
        paddingLeft: 0,
        paddingRight: 5,
        height: '65%',
        width: '90%',
        alignSelf: 'center',
    },
    containerVertical: {
        alignItems:'center',
    },
    userImage: {
        borderRadius: 250,
        borderColor: '#000000',
        borderWidth: 1,
        backgroundColor: '#45B9B9',
        height: 107,
        width: 100,
        marginLeft: 5,
        paddingBottom: 15,
        paddingLeft: '1%',
        alignContent: 'center',
        marginTop: '6%',
    },
    loginText: {
        height: 30,
        width: '100%',
        fontSize: 16,
        fontWeight: 'bold',
    },
    containerHorizontal: {
        flexDirection: 'row',
        width: '100%',
    },
    gradientBox: {
        height: 30,
        borderRadius: 10,
        width: '100%',
    },
    
    viewCentralizada: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 22,
      },

      janelaModal: {
        backgroundColor: '#A3D8EE',
        borderColor: 'black',
        borderWidth: 2,
        borderRadius: 15,
        paddingHorizontal: 15,
        paddingVertical: 25,
        width: '80%',
        alignSelf: 'center',
    },

    botaoCancelarModal:{
        height:'100%',
        width: '25%',
        backgroundColor:'#CC6666',
        borderColor: 'black',
        borderRadius: 15,
        borderWidth:2,
        alignItems:'center',
    },
    botaoConfirmarModal:{
        height:'100%',
        width: '25%',
        backgroundColor:'#45B9B9',
        borderColor: 'black',
        borderRadius: 15,
        borderWidth:2,
        alignItems:'center',
    },
    input: {
        height: 30,
        width: '100%',
        fontSize: 16,
        fontWeight: 'bold',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
        borderStyle: 'solid',
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: 'transparent',
        position: 'absolute',
    },
    botaoMostrarSenha: {
        width: '100%',
        height: '100%',
        // position:'absolute',
        //bottom: '-15%',
        // right:'-15%',
    },
    botaoLogin: {
        width: 40,
        aspectRatio: 1,
        backgroundColor: '#45B9B9',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'flex-end',
        borderRadius: 15,
        borderColor: 'black',
        borderWidth: 1,
        borderStyle: 'solid',
        position:'absolute',
        top: '3%',
        right:'3%',
    },
});

export default styles;