import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    containerMensagens: {
        backgroundColor: 'transparent',
        borderColor: '#0000000',
        borderWidth: 1,
        borderTopWidth: 0,
        borderBottomWidth: 0,
        paddingVertical: 10,
        paddingLeft: 0,
        paddingRight: 0,
        height: '70%',
        width: '100%',
    },
    containerBackground: {
        height: '100%',
        width: '100%',
    },
    containerJanelaMensagens:{
        height: '80%',
        width: '100%',
        paddingHorizontal: '4%',
    },
    userImage: {
        borderRadius: 105,
        borderColor: 'black',
        borderWidth: 1,
        backgroundColor: '#45B9B9',
        height: '70%',
        aspectRatio: 1,
        alignContent: 'center',
        justifyContent: 'center'
    },
    detalhesContatoContainer:{
        height: '25%',
        width: '100%',
        borderWidth: 1,
        backgroundColor: 'transparent',
        borderRadius: 15,
        borderBottomWidth: 2,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderColor: 'black',
        justifyContent: 'space-evenly',
        paddingHorizontal: 20,
        paddingBottom: '3%',
        alignItems: 'center',
    },

    contatoNome: {
        height: '30%',
        width: '100%',
        fontSize: 30,
        fontWeight: 'bold',
        justifyContent: 'center',
        paddingHorizontal: 10,
        marginBottom: '2%',
        textAlign:'center',
    },
    
    caixaMensagemContainer: {
        height: 50,
        width: '100%',
        justifyContent: 'space-around',
        //paddingHorizontal: 10,
        paddingBottom: 10,
        bottom: '1%',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderTopWidth: 0,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        flexDirection: 'row',
        shadowColor: '#5B8975',
        shadowOffset: { width: 0, height: 5 }
    },
    caixaInputMensagem: {
        height: '100%',
        width: '100%',
        fontSize: 22,
        borderRadius: 20,
        paddingHorizontal: 10,
    },
    
    inputContainer: {
        height: '100%',
        width: '80%',
        borderColor: 'black',
        borderRadius: 20,
        borderWidth: 1,
        borderStyle: 'solid',
        backgroundColor: '#45B9B9',
    },
    botaoEnviar: {
        borderRadius: 70,
        borderColor: 'black',
        borderWidth: 1,
        backgroundColor: '#45B9B9',
        height: '100%',
        aspectRatio: 1,
        alignContent: 'center',
        justifyContent: 'center',
    },
    background: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: '100%',
        width: '100%',
    },
});
